// ─────────────────────────────────────────────────────────────────────────────
// CrossFit Benchmark "The Girls"
// ─────────────────────────────────────────────────────────────────────────────
export const girlsWorkouts = [
  {
    id: 'Amanda',
    type: 'For Time',
    timecap: 15,
    description: '9-7-5 reps for time',
    exercises: [
      { name: 'Squat Snatches', reps: '9-7-5', weight: '61/43 kg' },
      { name: 'Ring Muscle-ups', reps: '9-7-5' },
    ],
  },
  {
    id: 'Angie',
    type: 'For Time',
    timecap: 40,
    description: 'For time — 100 reps van elk beweging, in volgorde',
    exercises: [
      { name: 'Pull-ups', reps: '100' },
      { name: 'Push-ups', reps: '100' },
      { name: 'Sit-ups', reps: '100' },
      { name: 'Air Squats', reps: '100' },
    ],
  },
  {
    id: 'Annie',
    type: 'For Time',
    timecap: 15,
    description: '50-40-30-20-10 reps for time',
    exercises: [
      { name: 'Double-unders', reps: '50-40-30-20-10' },
      { name: 'Sit-ups', reps: '50-40-30-20-10' },
    ],
  },
  {
    id: 'Barbara',
    type: 'For Time',
    timecap: 45,
    description: '5 rounds for time — 3 min rust tussen elke ronde',
    exercises: [
      { name: 'Pull-ups', reps: '20' },
      { name: 'Push-ups', reps: '30' },
      { name: 'Sit-ups', reps: '40' },
      { name: 'Air Squats', reps: '50' },
      { name: '— 3 min rest —', reps: '(×5 rondes)' },
    ],
  },
  {
    id: 'Chelsea',
    type: 'EMOM',
    timecap: 30,
    description: 'EMOM 30 min — elke minuut op de minuut',
    exercises: [
      { name: 'Pull-ups', reps: '5' },
      { name: 'Push-ups', reps: '10' },
      { name: 'Air Squats', reps: '15' },
    ],
  },
  {
    id: 'Cindy',
    type: 'AMRAP',
    timecap: 20,
    description: 'AMRAP 20 min',
    exercises: [
      { name: 'Pull-ups', reps: '5' },
      { name: 'Push-ups', reps: '10' },
      { name: 'Air Squats', reps: '15' },
    ],
  },
  {
    id: 'Diane',
    type: 'For Time',
    timecap: 15,
    description: '21-15-9 reps for time',
    exercises: [
      { name: 'Deadlifts', reps: '21-15-9', weight: '102.5/70 kg' },
      { name: 'Handstand Push-ups', reps: '21-15-9' },
    ],
  },
  {
    id: 'Elizabeth',
    type: 'For Time',
    timecap: 15,
    description: '21-15-9 reps for time',
    exercises: [
      { name: 'Squat Cleans', reps: '21-15-9', weight: '61/43 kg' },
      { name: 'Ring Dips', reps: '21-15-9' },
    ],
  },
  {
    id: 'Eva',
    type: 'For Time',
    timecap: 60,
    description: '5 rounds for time',
    exercises: [
      { name: 'Run', reps: '800 m' },
      { name: 'KB Swings', reps: '30', weight: '32 kg (2 pood)' },
      { name: 'Pull-ups', reps: '30' },
    ],
  },
  {
    id: 'Fran',
    type: 'For Time',
    timecap: 10,
    description: '21-15-9 reps for time — de meest iconische CrossFit WOD',
    exercises: [
      { name: 'Thrusters', reps: '21-15-9', weight: '43/30 kg' },
      { name: 'Pull-ups', reps: '21-15-9' },
    ],
  },
  {
    id: 'Grace',
    type: 'For Time',
    timecap: 10,
    description: 'For time — zo snel mogelijk',
    exercises: [
      { name: 'Clean & Jerks', reps: '30', weight: '61/43 kg' },
    ],
  },
  {
    id: 'Gwen',
    type: 'For Load',
    timecap: 30,
    description: '15-12-9 reps for load — ongebroken sets, rust naar behoefte',
    exercises: [
      { name: 'Clean & Jerks (unbroken)', reps: '15-12-9', weight: 'zo zwaar mogelijk' },
    ],
  },
  {
    id: 'Helen',
    type: 'For Time',
    timecap: 15,
    description: '3 rounds for time',
    exercises: [
      { name: 'Run', reps: '400 m' },
      { name: 'KB Swings', reps: '21', weight: '24/16 kg' },
      { name: 'Pull-ups', reps: '12' },
    ],
  },
  {
    id: 'Hope',
    type: 'For Reps',
    timecap: 9,
    description: '3 rounds — AMRAP stijl, per oefening 1 min',
    exercises: [
      { name: 'Burpees', reps: '1 min' },
      { name: 'Power Snatches', reps: '1 min', weight: '34 kg' },
      { name: 'Box Jumps', reps: '1 min', height: '24"' },
      { name: 'Thrusters', reps: '1 min', weight: '34 kg' },
      { name: 'Chest-to-Bar Pull-ups', reps: '1 min' },
    ],
  },
  {
    id: 'Isabel',
    type: 'For Time',
    timecap: 10,
    description: 'For time',
    exercises: [
      { name: 'Snatches', reps: '30', weight: '61/43 kg' },
    ],
  },
  {
    id: 'Jackie',
    type: 'For Time',
    timecap: 15,
    description: 'For time — chipper',
    exercises: [
      { name: 'Row', reps: '1000 m' },
      { name: 'Thrusters', reps: '50', weight: '20 kg' },
      { name: 'Pull-ups', reps: '30' },
    ],
  },
  {
    id: 'Karen',
    type: 'For Time',
    timecap: 20,
    description: 'For time',
    exercises: [
      { name: 'Wall-Ball Shots', reps: '150', weight: '9/6 kg' },
    ],
  },
  {
    id: 'Kelly',
    type: 'For Time',
    timecap: 45,
    description: '5 rounds for time',
    exercises: [
      { name: 'Run', reps: '400 m' },
      { name: 'Box Jumps', reps: '30', height: '24/20"' },
      { name: 'Wall-Ball Shots', reps: '30', weight: '9/6 kg' },
    ],
  },
  {
    id: 'Linda',
    type: 'For Time',
    timecap: 45,
    description: '10-9-8-7-6-5-4-3-2-1 reps for time — gewichten zijn lichaamsgewicht-gebaseerd',
    exercises: [
      { name: 'Deadlifts', reps: '10→1', weight: '1.5× lichaamsgewicht' },
      { name: 'Bench Press', reps: '10→1', weight: '1× lichaamsgewicht' },
      { name: 'Cleans', reps: '10→1', weight: '0.75× lichaamsgewicht' },
    ],
  },
  {
    id: 'Mary',
    type: 'AMRAP',
    timecap: 20,
    description: 'AMRAP 20 min',
    exercises: [
      { name: 'Handstand Push-ups', reps: '5' },
      { name: 'Pistols (afwisselend)', reps: '10' },
      { name: 'Pull-ups', reps: '15' },
    ],
  },
  {
    id: 'Nancy',
    type: 'For Time',
    timecap: 25,
    description: '5 rounds for time',
    exercises: [
      { name: 'Run', reps: '400 m' },
      { name: 'Overhead Squats', reps: '15', weight: '43/29 kg' },
    ],
  },
]

// ─────────────────────────────────────────────────────────────────────────────
// CrossFit Hero WODs — de meest bekende / meest gedaan
// ─────────────────────────────────────────────────────────────────────────────
export const heroWorkouts = [
  {
    id: 'Murph',
    type: 'For Time',
    timecap: 60,
    tribute: 'Navy Lt. Michael Murphy — KIA 28 juni 2005, Afghanistan',
    description: 'For time — met 9/6 kg gewichtsvest. Verdeel pull-ups, push-ups en squats naar behoefte.',
    exercises: [
      { name: 'Run', reps: '1 mile (1.6 km)' },
      { name: 'Pull-ups', reps: '100' },
      { name: 'Push-ups', reps: '200' },
      { name: 'Air Squats', reps: '300' },
      { name: 'Run', reps: '1 mile (1.6 km)' },
    ],
  },
  {
    id: 'DT',
    type: 'For Time',
    timecap: 30,
    tribute: 'Staff Sgt. Timothy P. Davis — KIA 20 februari 2009, Afghanistan',
    description: '5 rounds for time',
    exercises: [
      { name: 'Deadlifts', reps: '12', weight: '70/47.5 kg' },
      { name: 'Hang Power Cleans', reps: '9', weight: '70/47.5 kg' },
      { name: 'Push Jerks', reps: '6', weight: '70/47.5 kg' },
    ],
  },
  {
    id: 'Nate',
    type: 'AMRAP',
    timecap: 20,
    tribute: 'Chief Petty Officer Nate Hardy — KIA 4 februari 2008, Irak',
    description: 'AMRAP 20 min',
    exercises: [
      { name: 'Ring Muscle-ups', reps: '2' },
      { name: 'Handstand Push-ups', reps: '4' },
      { name: 'KB Swings', reps: '8', weight: '32 kg (2 pood)' },
    ],
  },
  {
    id: 'Jason',
    type: 'For Time',
    timecap: 40,
    tribute: 'SEAL SO1 Jason Dale Lewis — KIA 6 juli 2007, Irak',
    description: 'For time — aflopende squats met oplopende muscle-ups',
    exercises: [
      { name: 'Air Squats', reps: '100' },
      { name: 'Ring Muscle-ups', reps: '5' },
      { name: 'Air Squats', reps: '75' },
      { name: 'Ring Muscle-ups', reps: '10' },
      { name: 'Air Squats', reps: '50' },
      { name: 'Ring Muscle-ups', reps: '15' },
      { name: 'Air Squats', reps: '25' },
      { name: 'Ring Muscle-ups', reps: '20' },
    ],
  },
  {
    id: 'Josh',
    type: 'For Time',
    timecap: 30,
    tribute: 'Staff Sgt. Joshua Whitaker — KIA 15 mei 2007, Afghanistan',
    description: 'For time — 21-15-9',
    exercises: [
      { name: 'Overhead Squats', reps: '21-15-9', weight: '43/29 kg' },
      { name: 'Pull-ups', reps: '42-30-18' },
    ],
  },
  {
    id: 'JT',
    type: 'For Time',
    timecap: 20,
    tribute: 'Petty Officer 1st Class Jeff Taylor — KIA 28 juni 2005, Afghanistan',
    description: '21-15-9 reps for time',
    exercises: [
      { name: 'Handstand Push-ups', reps: '21-15-9' },
      { name: 'Ring Dips', reps: '21-15-9' },
      { name: 'Push-ups', reps: '21-15-9' },
    ],
  },
  {
    id: 'Michael',
    type: 'For Time',
    timecap: 40,
    tribute: 'Navy Lt. Michael McGreevy — KIA 28 juni 2005, Afghanistan',
    description: '3 rounds for time',
    exercises: [
      { name: 'Run', reps: '800 m' },
      { name: 'Back Extensions', reps: '50' },
      { name: 'Sit-ups', reps: '50' },
    ],
  },
  {
    id: 'Danny',
    type: 'AMRAP',
    timecap: 20,
    tribute: 'Officer Danny Faulkner — NYPD, gestorven in de lijn van dienst',
    description: 'AMRAP 20 min',
    exercises: [
      { name: 'Box Jumps', reps: '30', height: '24"' },
      { name: 'Push Press', reps: '20', weight: '52/36 kg' },
      { name: 'Pull-ups', reps: '30' },
    ],
  },
  {
    id: 'Jack',
    type: 'AMRAP',
    timecap: 20,
    tribute: 'Army Staff Sgt. Jack M. Martin III — KIA 29 augustus 2009, Afghanistan',
    description: 'AMRAP 20 min',
    exercises: [
      { name: 'Push Press', reps: '10', weight: '52/36 kg' },
      { name: 'KB Swings', reps: '10', weight: '24 kg (1.5 pood)' },
      { name: 'Box Jumps', reps: '10', height: '24"' },
    ],
  },
  {
    id: 'Ryan',
    type: 'For Time',
    timecap: 40,
    tribute: 'Cpl. Ryan C. McGhee — KIA 13 mei 2009, Irak',
    description: '5 rounds for time',
    exercises: [
      { name: 'Ring Muscle-ups', reps: '7' },
      { name: 'Burpees', reps: '21' },
    ],
  },
  {
    id: 'Griff',
    type: 'For Time',
    timecap: 30,
    tribute: 'Marine Sgt. Patrick Griffith — KIA 4 november 2006, Irak',
    description: 'For time — combinatie van vooruit en achteruit hardlopen',
    exercises: [
      { name: 'Run', reps: '800 m' },
      { name: 'Run backwards', reps: '400 m' },
      { name: 'Run', reps: '800 m' },
      { name: 'Run backwards', reps: '400 m' },
    ],
  },
  {
    id: 'Hansen',
    type: 'For Time',
    timecap: 45,
    tribute: 'Staff Sgt. Daniel Hansen — KIA 9 februari 2007, Irak',
    description: '5 rounds for time',
    exercises: [
      { name: 'KB Swings', reps: '30', weight: '32 kg (2 pood)' },
      { name: 'Burpees', reps: '30' },
      { name: 'Pull-ups', reps: '30' },
    ],
  },
  {
    id: 'Holleyman',
    type: 'For Time',
    timecap: 45,
    tribute: 'Staff Sgt. Aaron Holleyman — KIA 30 augustus 2004, Irak',
    description: '30 rounds for time',
    exercises: [
      { name: 'Wall-Ball Shots', reps: '5', weight: '9 kg' },
      { name: 'Handstand Push-ups', reps: '3' },
      { name: 'Power Cleans', reps: '1', weight: '102.5 kg' },
    ],
  },
  {
    id: 'Seven',
    type: 'For Time',
    timecap: 60,
    tribute: 'Zeven CIA-officieren omgekomen bij aanslag Camp Chapman — 30 december 2009',
    description: '7 rounds for time — ter ere van de 7 CIA-officers',
    exercises: [
      { name: 'Handstand Push-ups', reps: '7' },
      { name: 'Thrusters', reps: '7', weight: '61/43 kg' },
      { name: 'Knees-to-Elbows', reps: '7' },
      { name: 'Deadlifts', reps: '7', weight: '111/74 kg' },
      { name: 'Burpees', reps: '7' },
      { name: 'KB Swings', reps: '7', weight: '32 kg (2 pood)' },
      { name: 'Pull-ups', reps: '7' },
    ],
  },
  {
    id: 'Forrest',
    type: 'For Time',
    timecap: 45,
    tribute: 'Sgt. Maj. Robert Cottle — KIA 24 maart 2010, Afghanistan',
    description: '3 rounds for time',
    exercises: [
      { name: 'L-Pull-ups', reps: '20' },
      { name: 'Toes-to-Bar', reps: '30' },
      { name: 'Burpees', reps: '40' },
      { name: 'Run', reps: '800 m' },
    ],
  },
  {
    id: 'Chad',
    type: 'For Time',
    timecap: 90,
    tribute: 'SEAL Chad Michael Wilkinson — gestorven 29 oktober 2018',
    description: 'For time — 1.000 box step-ups met 9 kg gewichtsvest',
    exercises: [
      { name: 'Box Step-ups', reps: '1.000', height: '20" · met 9 kg vest' },
    ],
  },
  {
    id: 'Badger',
    type: 'For Time',
    timecap: 60,
    tribute: 'Chief Petty Officer Mark Carter — KIA 11 december 2007, Irak',
    description: '3 rounds for time',
    exercises: [
      { name: 'Squat Cleans', reps: '30', weight: '43/29 kg' },
      { name: 'Pull-ups', reps: '30' },
      { name: 'Run', reps: '800 m' },
    ],
  },
  {
    id: 'Whitten',
    type: 'For Time',
    timecap: 60,
    tribute: 'Capt. James Whitten — KIA 2 februari 2007, Irak',
    description: '5 rounds for time',
    exercises: [
      { name: 'Run', reps: '400 m' },
      { name: 'Overhead Squats', reps: '15', weight: '43/29 kg' },
      { name: 'Pull-ups', reps: '15' },
      { name: 'Burpees', reps: '15' },
      { name: 'DB Squat Cleans', reps: '15', weight: '18/12 kg' },
    ],
  },
  {
    id: 'Hotshots 19',
    type: 'For Time',
    timecap: 60,
    tribute: 'De 19 Granite Mountain Hotshots brandweerlieden — omgekomen 30 juni 2013, Yarnell Hill Fire, Arizona',
    description: '6 rounds for time',
    exercises: [
      { name: 'Run', reps: '400 m' },
      { name: 'Deadlifts', reps: '19', weight: '70/47.5 kg' },
      { name: 'Pull-ups', reps: '19' },
    ],
  },
]
