// ─────────────────────────────────────────────────────────────────────────────
// Oefeningen database — ~200 oefeningen verdeeld over 9 categorieën
// Elke oefening heeft: name, reps [beginner, intermediate, advanced],
//   optioneel: unit, weight (♂/♀), height, scaled
// ─────────────────────────────────────────────────────────────────────────────

export const exercises = {

  Gymnastics: [
    { name: 'Pull-ups',                  reps: [5, 10, 15],   scaled: 'Ring Rows' },
    { name: 'Chest-to-Bar Pull-ups',     reps: [3, 7, 12],    scaled: 'Pull-ups' },
    { name: 'Bar Muscle-ups',            reps: [2, 4, 7],     scaled: 'Chest-to-Bar Pull-ups' },
    { name: 'Ring Muscle-ups',           reps: [2, 4, 6],     scaled: 'Ring Rows' },
    { name: 'Kipping Pull-ups',          reps: [7, 12, 20],   scaled: 'Ring Rows' },
    { name: 'Strict Pull-ups',           reps: [3, 6, 10],    scaled: 'Band Pull-ups' },
    { name: 'L-sit Pull-ups',            reps: [3, 5, 8] },
    { name: 'Handstand Push-ups',        reps: [5, 9, 15],    scaled: 'Pike Push-ups' },
    { name: 'Strict HSPU',               reps: [3, 6, 10],    scaled: 'Pike Push-ups' },
    { name: 'Kipping HSPU',              reps: [5, 10, 15],   scaled: 'DB Shoulder Press' },
    { name: 'Toes-to-Bar',               reps: [8, 12, 20],   scaled: 'Hanging Knee Raises' },
    { name: 'Knees-to-Elbows',           reps: [8, 12, 18],   scaled: 'Hanging Knee Raises' },
    { name: 'Ring Dips',                 reps: [6, 10, 15],   scaled: 'Box Dips' },
    { name: 'Bar Dips',                  reps: [8, 12, 18],   scaled: 'Box Dips' },
    { name: 'Strict Ring Dips',          reps: [4, 7, 12],    scaled: 'Box Dips' },
    { name: 'Wall Walks',                reps: [2, 4, 7] },
    { name: 'Handstand Walk',            reps: [5, 10, 20],   unit: 'm' },
    { name: 'Rope Climbs',               reps: [1, 2, 4],     unit: 'climbs' },
    { name: 'Legless Rope Climbs',       reps: [1, 2, 3],     unit: 'climbs' },
    { name: 'Skin the Cat',              reps: [3, 5, 8] },
    { name: 'Ring Rows',                 reps: [8, 12, 18] },
    { name: 'Strict Ring Rows',          reps: [6, 10, 15] },
    { name: 'Hanging L-sit',             reps: [15, 25, 40],  unit: 'sec' },
    { name: 'Bar Hang',                  reps: [20, 40, 60],  unit: 'sec' },
  ],

  Weightlifting: [
    { name: 'Power Cleans',              reps: [3, 5, 7],     weight: '60/40 kg' },
    { name: 'Squat Cleans',              reps: [2, 4, 6],     weight: '70/47 kg' },
    { name: 'Hang Power Cleans',         reps: [4, 6, 9],     weight: '55/37 kg' },
    { name: 'Hang Squat Cleans',         reps: [2, 4, 6],     weight: '65/43 kg' },
    { name: 'Power Snatches',            reps: [3, 5, 7],     weight: '43/30 kg' },
    { name: 'Squat Snatches',            reps: [2, 3, 5],     weight: '50/35 kg' },
    { name: 'Hang Power Snatches',       reps: [3, 5, 8],     weight: '40/27 kg' },
    { name: 'Clean & Jerks',             reps: [2, 4, 7],     weight: '61/43 kg' },
    { name: 'Split Jerks',               reps: [2, 3, 5],     weight: '70/47 kg' },
    { name: 'Push Jerks',                reps: [3, 5, 8],     weight: '52/35 kg' },
    { name: 'Deadlifts',                 reps: [6, 9, 12],    weight: '100/70 kg' },
    { name: 'Romanian Deadlifts',        reps: [8, 10, 15],   weight: '70/47 kg' },
    { name: 'Sumo Deadlifts',            reps: [5, 8, 12],    weight: '90/60 kg' },
    { name: 'Back Squats',               reps: [5, 8, 10],    weight: '80/55 kg' },
    { name: 'Front Squats',              reps: [4, 7, 10],    weight: '60/40 kg' },
    { name: 'Overhead Squats',           reps: [4, 6, 10],    weight: '43/29 kg' },
    { name: 'Thrusters',                 reps: [6, 9, 12],    weight: '43/30 kg' },
    { name: 'Push Press',                reps: [6, 9, 12],    weight: '50/35 kg' },
    { name: 'Strict Press',              reps: [5, 7, 10],    weight: '40/27 kg' },
    { name: 'Bench Press',               reps: [5, 8, 12],    weight: '70/47 kg' },
    { name: 'Pendlay Rows',              reps: [5, 8, 10],    weight: '60/40 kg' },
    { name: 'Good Mornings',             reps: [8, 10, 15],   weight: '40/27 kg' },
    { name: 'Barbell Hip Thrusts',       reps: [8, 12, 15],   weight: '80/55 kg' },
    { name: 'Power Clean + Front Squat', reps: [2, 3, 5],     weight: '60/40 kg' },
    { name: 'Clean Pull',                reps: [3, 5, 7],     weight: '80/55 kg' },
  ],

  Cardio: [
    { name: 'Row',                       reps: [200, 400, 500],   unit: 'm' },
    { name: 'Row',                       reps: [400, 800, 1000],  unit: 'm' },
    { name: 'Calories Row',              reps: [10, 15, 20],      unit: 'cal' },
    { name: 'Assault Bike',              reps: [8, 12, 18],       unit: 'cal' },
    { name: 'Assault Bike',              reps: [12, 20, 30],      unit: 'cal' },
    { name: 'Echo Bike',                 reps: [8, 12, 18],       unit: 'cal' },
    { name: 'Ski Erg',                   reps: [200, 400, 500],   unit: 'm' },
    { name: 'Calories Ski Erg',          reps: [8, 12, 18],       unit: 'cal' },
    { name: 'Double-unders',             reps: [25, 50, 75] },
    { name: 'Double-unders',             reps: [30, 60, 100] },
    { name: 'Single-unders',             reps: [50, 100, 150] },
    { name: 'Single-unders',             reps: [75, 150, 200] },
    { name: 'Jump Rope',                 reps: [30, 60, 90],      unit: 'sec' },
  ],

  Bodyweight: [
    { name: 'Burpees',                   reps: [5, 10, 15] },
    { name: 'Bar-facing Burpees',        reps: [5, 8, 12] },
    { name: 'Lateral Burpees',           reps: [5, 8, 12] },
    { name: 'Burpee Box Jump-overs',     reps: [4, 7, 10],    height: '60/50 cm' },
    { name: 'Air Squats',                reps: [15, 25, 35] },
    { name: 'Squat Jumps',               reps: [10, 15, 20] },
    { name: 'Pistols',                   reps: [4, 7, 10],    scaled: 'Assisted Pistols' },
    { name: 'Walking Lunges',            reps: [10, 16, 24] },
    { name: 'Reverse Lunges',            reps: [10, 16, 20] },
    { name: 'Step-ups',                  reps: [10, 14, 20],  height: '60/50 cm' },
    { name: 'Push-ups',                  reps: [10, 15, 25] },
    { name: 'Diamond Push-ups',          reps: [8, 12, 18] },
    { name: 'Pike Push-ups',             reps: [8, 12, 16] },
    { name: 'Clapping Push-ups',         reps: [5, 8, 12] },
    { name: 'Sit-ups',                   reps: [15, 25, 35] },
    { name: 'AbMat Sit-ups',             reps: [15, 25, 40] },
    { name: 'Jumping Jacks',             reps: [25, 40, 60] },
    { name: 'Mountain Climbers',         reps: [20, 30, 40] },
    { name: 'High Knees',                reps: [20, 30, 40],  unit: 'reps' },
    { name: 'Hip Extensions',            reps: [12, 18, 25] },
    { name: 'Superman',                  reps: [10, 15, 20] },
    { name: 'Bear Crawl',                reps: [10, 15, 20],  unit: 'm' },
    { name: 'Inchworm',                  reps: [5, 8, 12] },
    { name: 'Glute Bridges',             reps: [15, 20, 30] },
    { name: 'Single-leg Glute Bridge',   reps: [8, 12, 18],   unit: 'per been' },
  ],

  Kettlebell: [
    { name: 'KB Swings',                 reps: [12, 20, 30],  weight: '24/16 kg' },
    { name: 'KB American Swings',        reps: [10, 15, 25],  weight: '24/16 kg' },
    { name: 'KB Goblet Squats',          reps: [8, 12, 18],   weight: '24/16 kg' },
    { name: 'KB Snatches',               reps: [5, 8, 12],    weight: '24/16 kg' },
    { name: 'KB Clean & Press',          reps: [4, 6, 10],    weight: '24/16 kg' },
    { name: 'KB Turkish Get-ups',        reps: [2, 4, 6],     weight: '16/12 kg' },
    { name: 'KB Farmers Carry',          reps: [20, 30, 50],  unit: 'm' },
    { name: 'KB Overhead Carry',         reps: [15, 25, 40],  unit: 'm',  weight: '20/14 kg' },
    { name: 'KB Single-arm Row',         reps: [8, 12, 16],   weight: '24/16 kg' },
    { name: 'KB Windmill',               reps: [3, 5, 8],     weight: '16/12 kg' },
    { name: 'KB Sumo Deadlift',          reps: [10, 15, 20],  weight: '32/24 kg' },
    { name: 'KB Alternating Lunges',     reps: [8, 12, 18],   weight: '24/16 kg' },
    { name: 'KB Push Press',             reps: [6, 9, 12],    weight: '24/16 kg' },
    { name: 'Double KB Front Squat',     reps: [5, 8, 12],    weight: '2×20/2×14 kg' },
    { name: 'KB Deadlift',               reps: [8, 12, 18],   weight: '32/24 kg' },
    { name: 'KB Figure-8',               reps: [10, 16, 24],  weight: '20/14 kg' },
  ],

  Dumbbell: [
    { name: 'DB Snatches',               reps: [5, 8, 12],    weight: '22.5/15 kg' },
    { name: 'DB Hang Clean & Jerks',     reps: [4, 7, 10],    weight: '22.5/15 kg' },
    { name: 'DB Thrusters',              reps: [6, 10, 14],   weight: '22.5/15 kg' },
    { name: 'DB Renegade Rows',          reps: [5, 8, 12],    weight: '22.5/15 kg' },
    { name: 'DB Step-ups',               reps: [8, 12, 16],   weight: '22.5/15 kg',  height: '60/50 cm' },
    { name: 'DB Deadlifts',              reps: [8, 12, 18],   weight: '2×22.5/2×15 kg' },
    { name: 'DB Push Press',             reps: [8, 12, 16],   weight: '2×20/2×14 kg' },
    { name: 'DB Bench Press',            reps: [8, 10, 15],   weight: '2×22.5/2×15 kg' },
    { name: 'DB Bent-over Rows',         reps: [8, 12, 16],   weight: '2×22.5/2×15 kg' },
    { name: 'DB Front Squats',           reps: [8, 12, 16],   weight: '2×22.5/2×15 kg' },
    { name: 'DB Overhead Squats',        reps: [5, 8, 12],    weight: '22.5/15 kg' },
    { name: 'DB Reverse Lunges',         reps: [8, 12, 18],   weight: '2×20/2×14 kg' },
    { name: 'DB Box Step-overs',         reps: [8, 12, 16],   weight: '22.5/15 kg',  height: '60/50 cm' },
    { name: 'DB Bicep Curls',            reps: [10, 14, 20],  weight: '2×15/2×10 kg' },
    { name: 'DB Lateral Raises',         reps: [10, 14, 20],  weight: '2×10/2×7 kg' },
    { name: 'DB Floor Press',            reps: [8, 12, 16],   weight: '2×22.5/2×15 kg' },
    { name: 'DB Arnold Press',           reps: [8, 10, 14],   weight: '2×15/2×10 kg' },
    { name: 'DB Walking Lunges',         reps: [10, 14, 20],  weight: '2×20/2×14 kg' },
  ],

  Core: [
    { name: 'Plank',                     reps: [25, 45, 60],  unit: 'sec' },
    { name: 'Side Plank',                reps: [20, 35, 50],  unit: 'sec' },
    { name: 'Hollow Body Hold',          reps: [20, 35, 50],  unit: 'sec' },
    { name: 'Hollow Body Rocks',         reps: [10, 20, 30] },
    { name: 'V-ups',                     reps: [10, 15, 22] },
    { name: 'Tuck-ups',                  reps: [12, 18, 25] },
    { name: 'GHD Sit-ups',               reps: [8, 15, 25] },
    { name: 'AbMat Sit-ups',             reps: [15, 25, 40] },
    { name: 'Russian Twists',            reps: [15, 22, 30] },
    { name: 'L-sit',                     reps: [10, 20, 35],  unit: 'sec' },
    { name: 'Dragon Flag',               reps: [3, 5, 8] },
    { name: 'Dead Bug',                  reps: [8, 12, 18] },
    { name: 'Flutter Kicks',             reps: [20, 30, 40],  unit: 'sec' },
    { name: 'Scissor Kicks',             reps: [15, 25, 35] },
    { name: 'Hanging Knee Raises',       reps: [10, 15, 22] },
    { name: 'Arch Body Hold',            reps: [20, 35, 50],  unit: 'sec' },
    { name: 'Pallof Press',              reps: [8, 12, 16] },
    { name: 'GHD Hip Extensions',        reps: [10, 15, 20] },
    { name: 'Superman Hold',             reps: [20, 35, 50],  unit: 'sec' },
    { name: 'Bicycle Crunches',          reps: [15, 25, 40] },
  ],

  Plyometrics: [
    { name: 'Box Jumps',                 reps: [8, 12, 18],   height: '60/50 cm' },
    { name: 'Box Jump-overs',            reps: [8, 12, 18],   height: '60/50 cm' },
    { name: 'Lateral Box Jumps',         reps: [8, 12, 16],   height: '60/50 cm' },
    { name: 'Step-ups',                  reps: [10, 16, 22],  height: '60/50 cm' },
    { name: 'Depth Jumps',               reps: [5, 8, 12] },
    { name: 'Broad Jumps',               reps: [6, 10, 14] },
    { name: 'Jump Squats',               reps: [8, 14, 20] },
    { name: 'Tuck Jumps',                reps: [8, 12, 18] },
    { name: 'Lateral Bounds',            reps: [8, 12, 18] },
    { name: 'Bounding',                  reps: [20, 30, 40],  unit: 'm' },
    { name: 'Single-leg Box Jumps',      reps: [4, 6, 10],    height: '50/40 cm' },
    { name: 'Hurdle Hops',               reps: [6, 10, 15] },
    { name: 'Speed Skaters',             reps: [10, 16, 24] },
    { name: 'Ankle Jumps',               reps: [15, 25, 35] },
    { name: 'Stair Hops',                reps: [6, 10, 16] },
  ],

  Running: [
    { name: 'Run',                       reps: [200, 400, 800],   unit: 'm' },
    { name: 'Run',                       reps: [400, 800, 1200],  unit: 'm' },
    { name: 'Run',                       reps: [800, 1200, 1600], unit: 'm' },
    { name: 'Run',                       reps: [1, 2, 3],         unit: 'km' },
    { name: 'Sprint',                    reps: [50, 100, 200],    unit: 'm' },
    { name: 'Sprint',                    reps: [100, 200, 400],   unit: 'm' },
    { name: 'Hill Sprint',               reps: [3, 5, 8],         unit: '× heuvel' },
    { name: 'Shuttle Run',               reps: [4, 6, 10],        unit: '× 25m' },
    { name: 'Tempo Run',                 reps: [400, 800, 1200],  unit: 'm' },
    { name: 'Run',                       reps: [3, 5, 8],         unit: '× 200m' },
  ],
}

// ─────────────────────────────────────────────────────────────────────────────
// WOD namen — 60 unieke namen
// ─────────────────────────────────────────────────────────────────────────────
export const wodNames = [
  'DELTA','STORM','GRINDER','BLAZE','IRON','FURY','BEAST',
  'INFERNO','HAMMER','TITAN','VIPER','GHOST','APEX','FORGE',
  'RUSH','THUNDER','RAMPAGE','COLOSSUS','SPARTAN','REAPER',
  'ANVIL','CLUTCH','SAVAGE','OMEGA','SIGNAL','BLUNT','RIGOR',
  'STRIKE','CIRCUIT','FRENZY','TORQUE','VOLTAGE','EMBER',
  'FRACTURE','HAVOC','IMPACT','KINETIC','LANCER','MERCILESS',
  'NOVA','OFFSET','PINNACLE','QUARRY','RIPTIDE','SHOCKWAVE',
  'TEMPEST','UPLIFT','VECTOR','WARPATH','XENITH','ZEAL',
  'ALPINE','BULLET','CARBON','DYNAMO','ECLIPSE','FLASHPOINT',
]

// ─────────────────────────────────────────────────────────────────────────────
// Format beschrijvingen
// ─────────────────────────────────────────────────────────────────────────────
export const formatDescs = {
  AMRAP:      'Zoveel rondes en reps als mogelijk binnen de tijdslimiet.',
  'For Time': 'Voltooi alle rondes zo snel mogelijk.',
  EMOM:       'Elke minuut op de minuut — start aan het begin van elke minuut.',
  Chipper:    'Van boven naar beneden — elke beweging één keer.',
  Ladder:     'Verhoog reps elke ronde (1 – 2 – 3 – ... – N).',
}

// ─────────────────────────────────────────────────────────────────────────────
// Tips — 30 unieke coachingstips
// ─────────────────────────────────────────────────────────────────────────────
export const tips = [
  'Behoud je techniek ook als je moe bent — kwaliteit boven kwantiteit.',
  'Doe een warming-up van 5 minuten voor je start.',
  'Noteer je score — de volgende keer wil je beter doen.',
  'Schaal gerust als dat nodig is. Jij kent je lichaam het best.',
  'Steady pace in de eerste helft, push in de tweede helft.',
  'Goede ademhaling is key: uitademen bij inspanning.',
  'Eet 1-2 uur voor training iets lichtverteerbaar.',
  'Leg je barbell klaar met het juiste gewicht voor de start.',
  'Break sets vroeg om te grote rust later te vermijden.',
  'Visualiseer de workout voor je begint — elke beweging.',
  'Hydrateer goed: minstens 500ml water voor de training.',
  'Focus op je heupen bij Olympic lifts — drive vanuit de heupen.',
  'Bij AMRAP: houd bij na elke ronde hoeveel je hebt gedaan.',
  'Kleine sets met korte rust slaan grote sets met lange rust.',
  'Kijk naar de tijd halverwege — pas je pace dan aan.',
  'Druk je voeten actief in de vloer bij squats.',
  'Houd je core strak bij iedere beweging — ook bij cardio.',
  'Kip pas als je de strict versie beheerst.',
  'Schoudermobiliteit is cruciaal bij overhead-bewegingen.',
  'Rust na de training is even belangrijk als de training zelf.',
  'Log je WODs — progressie zie je pas over langere tijd.',
  'Eet voldoende eiwitten (1.6-2g/kg) voor spierherstel.',
  'Foam rol na de training om spierpijn te beperken.',
  'Warm je polsen op voor hangende en overhead bewegingen.',
  'Kijk recht vooruit bij deadlifts — neutrale wervelkolom.',
  'Push de vloer van je af bij push-ups — schouderbladen actief.',
  'De lockout telt: strek heupen en knieën volledig.',
  'Verander je grip-breedte eens bij pull-ups voor variatie.',
  'Concentreer je op je zwakste beweging — dat is waar je wint.',
  'Slapen is het beste herstelprotocol dat bestaat.',
]
